// - Get question text label on stackoverflow's home page 
// - An example using pure jQuery
function getQuestionTexts() {
    let questionTexts = [] // new Array()

    $(".question-hyperlink").each(function(index, questionHyperlink){
        if(!$(questionHyperlink).hasClass("mb0"))
            questionTexts.push($(questionHyperlink).text())
    })

    return questionTexts
}

console.log(JSON.stringify(getQuestionTexts(), null, 4))
/*
[
    "Error while rendering an array.map() in React",
    "What options are available for video restreaming (eg. video clips from IP cameras) to all browsers? Is there any shareware available?",
    "awk/sed find then find again from that point",
    "Why can't I install hashlib with pip in python 3 for Windows?",
    "How do I add a watermark to multiple images using bitmap",
    "Can't get Unity Firebase userID",
    "What is difference of customization user model between AbstractBaseUser and AbstractUser",
    "How to make columns height adjustable to another an element suing Flexbox",
    "Javascript ES6 Intl. Date/Time Formatting",
    "Script to copy formulas when inserting row at the top - Google Sheets",
    "Is there a way to combine Excel workbooks into one Master workbook within python?",
    "How to adjust the size of a label depending on how much text is inputted kivy",
    "Is the following prime's algorithm correct?",
    "Open Amazone Prime Video series and directly enter Amazons continue watching function",
    "Retrieve contacts along with profile pic in batches using Graph API",
    "grunt syntax error issue on running grunt task",
    "trigger of loading recaptcha library only when user interacts but not getting the value in hidden input field",
    "Click outside angular component",
    "SqlBulkCopy DataTables as they are added to a DataSet",
    "Cannot resolve keyword 'tag' into field",
    "Asp.net MVC : Pass a value from webgrid text box column to the controller",
    "Getting lookup value from MS Access with pyodbc",
    "How do prevent the image in the background from zooming in modal mode?",
    "How to enable inline execution (chrome extension)",
    "Problems with Getting Response on the deployed bot;",
    "“Invalid directory on URL” while trying to use path created using New-PSDrive in Powershell",
    "Setting appropriate rpath for cmake project at install time",
    "Elasticsearch synonyms only for a certain field",
    "Which PHP Array Function to Use?",
    "How to fix “Arguments to CompositeDisposable.add must have a .dispose() method” when enabling the Omnisharp-atom package",
    "Issue with fetching site info of a microsoft teams group",
    "Django not recognising module import/ app folder",
    "show element in v-for list: VueJS",
    "How to install python3.6 on aws ec2 instance",
    "Error when enter down the line in TinyMCE",
    "How could I run tensorflow on windows 10? I have the gpu Geforce gtx 1650. Can I run tensorflow on it? if yes, then how?",
    "An error occurred in MPI_Comm_rank , reported by process [200015873,5]",
    "Add Clickable links in Calculation filed in Podio",
    "Bootstrap Collapsed Menu Links Not Working on Mobile Devices",
    "How can I Use LINE Notify to send image only",
    "Trouble exposing port on Azure Container Instance",
    "Is there a way to change the format of the excel date? [duplicate]",
    "python2.7 missing standard dbm module when install by conda",
    "unit testing Mail::send()",
    "How send message on swoole (websocket extension for php) from php to browser?",
    "In a multichannel chat application how can I display messages pertaining only to a specific chat channel?",
    "Adding TextGeometry THREE.js by For Loop",
    "Django celery group is not executing task even after receiving it when the number of tasks are more than number of cores",
    "How to imprt django-taggit tag in django-import-export",
    "Microsoft.Data.SqlClient vs System.Data.SqlClient",
    "How to convert dask dataframe to scipy csr matrix?",
    "Add a calculated column to a Laravel Eloquent model and sort and/or filter on that column",
    "How to allow unique Laravel Facade instances when using Builder pattern?",
    "HTML5 canvas Showing lines when drawing",
    "What is Endpoint Discovery?",
    "Ansible - Access output of a shell command with with_items",
    "Does the Laravel Mix Polyfill extension not include the String.includes method?",
    "Saving output as a video in opencv python",
    "Why does calling a shared memory object multiple times with shm_open create the object at multiple addresses?",
    "Automated simulation of Clicks for Extension setup",
    "Dialogflow Fulfilment with news API",
    "500 error when calling the function app endpoint via postman",
    "Running Keras LSTM Model In Django Returns 'thread._local' object has no attribute 'value'",
    "Using add_widget in the kv file",
    "How to implement choose squares with street signs reCAPTCHA",
    "Editing profile in django",
    "How to Soak Test Selenium Scripts",
    "Django Json like button and counting likes isn't working",
    "python _ Unable to filter text on selected column",
    "dataset creation using feature extraction from text",
    "With VueJS Cli how should do to have a variable common to all pages and be able to watch it in a page",
    "Can I sort with Firebase Firestore child with the Python SDK?",
    "How to get rid of escape sequence and custom classes when scraping backlinks in Python with BeautifulSoup?",
    "How to import auth.User on django-import/export",
    "using clause where within nested structure",
    "Slider with adding active class",
    "Parse pdf file for remote url using fpdi",
    "How to get a color-histogramm of the hue-values by using skimage instead OpenCV?",
    "Import (cannot import name 'ResolveInfo' from 'graphql') error when using newest graphene and graphene-django version",
    "How can I position two buttons on top of the background side by side and at the bottom of the screen in React Native?",
    "get all input element ids from view and pass them to action method in controller mvc5",
    "shutil.rmtree does not remove directory",
    "How to visualise multigraph using networkx?",
    "How can I make my slidershow protect its aspect ratio while shrinking?",
    "Python 3.7.3 / Django 3: 'ascii' codec can't encode character '\\xe8' in position 17: ordinal not in range(128)",
    "Multiple Inputs to a list [closed]",
    "How to check whether my image is RGB format or BGR format in python? How do i convert them and viceversa?",
    "Django project has an internal 'lib' folder that has all Independence. How can i use .bash_profile project link dependencies",
    "How to handle local state when using relay?",
    "Django: Building dynamic Q queries for related tables",
    "Error react-native-router-flux doesnt work",
    "How to add custom left-link models to wagtail admin page",
    "'Incorrect Header Check' when trying to receive data from google sheets using 'google-spreadsheet'",
    "Adding new sheet to 2000 xlsx files - Openpyxl is very slow",
    "Pandas code to keep columns which are zeros after pivot",
    "Changing x-axis of a datetime e.g trimming a graph with matplotlib in python"
]
*/